config/routes.rb
Rails.application.routes.draw do
  
    root "pages#home"
    
    get 'pages/home', to: "pages#home"
   
    resources :recipes do
        resources :comments, only: [:create]
    end
    
    mount ActionCable.server => '/cable'
    get '/chat', to: 'chatrooms#show'
   
   get '/signup', to: 'chefs#new'
   resources :chefs, except: [:new]

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    
    resources :ingredients, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<!--<div class="footer">
  <p>Adept Solutions@2017</p>
 </div>-->

app/views/layouts/_messages.html.erb
<dic class="row">
<div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %> ">
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
        </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
        <li><%= link_to "Chefs", chefs_path %></li>
        <li><%= link_to "All Recipes", recipes_path %></li>
        <%  if logged_in? %>
        <li><%= link_to "ChefChat", chat_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add a Recipe", new_recipe_path %></li>
            
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <%  end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ingredients <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Ingredients", ingredients_path %></li>
            <%  Ingredient.all.each do |ingredient| %>
            <li><%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "New Ingredient", new_ingredient_path %></li>
          </ul>
        </li>
      </ul>
      <!--<form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <ul class="nav navbar-nav navbar-right">
        
        <%  if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_chef.chefname.capitalize %>'s Profile <%=" Admin" if current_chef.admin? %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "View your profile", chef_path(current_chef) %></li>
            <li><%= link_to "Edit your profile", edit_chef_path(current_chef) %></li>
            <!--<li><a href="#">Something else here</a></li>-->
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
          </ul>
        </li>
        <% else  %>
          <li><%= link_to "Log in", login_path  %></li>
          <li><%= link_to "Register", signup_path  %></li>
        <%  end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
    </div>
    <div>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>